# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7vx485tffg1157-1
set_param project.compositeFile.enableAutoGeneration 0
read_vhdl D:/Projects_SisDigAva/P01_Vivado_Test/P01_Vivado_Test.srcs/sources_1/new/Top.vhd
set_property webtalk.parent_dir D:/Projects_SisDigAva/P01_Vivado_Test/P01_Vivado_Test.data/wt [current_project]
set_property parent.project_dir D:/Projects_SisDigAva/P01_Vivado_Test [current_project]
synth_design -top Top -part xc7vx485tffg1157-1
write_checkpoint Top.dcp
report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb
